Develop
C485/CocoJumper pull request #41
Opened 2019-05-28 13:44 UTC by Kraviecc

#39

2019-05-28 18:12 UTC, C485 requested changes
Move this one line up and it's ready

2019-05-28 18:12 UTC, C485 commented on CocoJumper/Commands/CocoJumperCommandPackage.cs
> +            await CocoJumper.Commands.CocoJumperWordSearchCommand.InitializeAsync(this);
Move this line one up

2019-05-28 18:12 UTC, C485 commented on CocoJumper/Commands/CocoJumperWordSearchCommand.cs
> +            OnKeyboardAction(this, null, KeyEventType.KeyPress);
It's necessary?

2019-05-28 20:19 UTC, Kraviecc commented on CocoJumper/Commands/CocoJumperWordSearchCommand.cs
> +            OnKeyboardAction(this, null, KeyEventType.KeyPress);
Yes, it's auto-searching mode where you don't literally press additional key to invoke searching. So we have to immediately invoke searching through view when pressing CTRL + ALT + ' (or rather parsing view to retrieve words and letters connected with them) and render markers.

2019-05-29 08:28 UTC, C485 submitted a review, later dismissed

2019-05-29 08:34 UTC, C485 approved these changes

2019-05-29 08:46 UTC, merged

2019-05-29 08:49 UTC, Kraviecc commented
Closes #39